[project]
name = "huginn"
dynamic = ["version"]
description = "A Python-native, async-first test automation framework for network infrastructure, servers, and applications."
readme = "README.md"
authors = [
    { name = "Christopher Hart", email = "christopherjhart95@gmail.com" },
    { name = "Andrea Testino", email = "aitestino@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "typer>=0.20.0",
    "aiohttp>=3.13.3",
    "jinja2>=3.1.6",
    "markdown>=3.8.2",
    "pyyaml>=6.0.3",
    "scrapli-netconf[asyncssh]>=2026.1.12",
    "scrapli[asyncssh]>=2026.2.20",
]

[project.scripts]
huginn = "huginn:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/huginn/_version.py"

[dependency-groups]
dev = [
    "bandit>=1.9.2",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.9",
    "ty>=0.0.29",
    "xenon>=0.9.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
exclude = ["src/huginn/_version.py"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "W",  # pycodestyle warnings
    "C90",# flake8-mccabe complexity
    "N",  # pep8-naming
    "UP", # pyupgrade
    "ANN",# flake8-annotations
    "D",  # pydocstyle
    "T",  # flake8-print (includes T201 for pdb, replacing debug-statements hook)
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
combine-as-imports = true
